[template]
files = [
    # All SecOps Repos
    ".gitattributes",
    ".github/workflows/pr_reminder.yml",
    ".github/workflows/cleanup.yml",
    "CODE_OF_CONDUCT.md",
    "SECURITY.md",
    # All Python Repos
    ".gitignore",
    "Makefile",
]
