[source]
url = 'https://raw.githubusercontent.com/techservicesillinois/secdev-template-repository/refs/heads/feature/sync/'  # From #22
# url = 'https://github.com/techservicesillinois/secdev-template-python/blob/main/'
