# This file configures `borg` when this repository is used as a source.
# This file should only be present in a template repository.

# If this file is present in a child repository, it should be deleted.

[template]
files = [
    # All SecOps Repos
    ".gitattributes",
    ".github/workflows/pr_reminder.yml",
    ".github/workflows/cleanup.yml",
    "CODE_OF_CONDUCT.md",
    "SECURITY.md",
    # All Python Repos
    ".gitignore",
    "Makefile",
]
